import 'dart:developer' as developer;
import 'dart:async';
import 'package:dio/dio.dart';
import '../../../core/models/voucher_scan.dart';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:mobile_scanner/mobile_scanner.dart';

import '../../../core/network/offer_api_service.dart';
import '../../../core/theme/app_theme.dart';

/// Phase 6 — Worker QR scanner.
///
/// Workers point the camera at a customer's claimed-offer QR code
/// (generated by POST /offers/{id}/claim). The decoded voucher code is sent
/// to POST /offers/redeem-by-code to instantly redeem the offer.
class QrScannerScreen extends ConsumerStatefulWidget {
  final String? venueId;

  const QrScannerScreen({super.key, this.venueId});

  @override
  ConsumerState<QrScannerScreen> createState() => _QrScannerScreenState();
}

class _QrScannerScreenState extends ConsumerState<QrScannerScreen>
    with WidgetsBindingObserver {
  final MobileScannerController _controller = MobileScannerController(
    detectionSpeed: DetectionSpeed.normal,
    detectionTimeoutMs: 500,
  );
  final TextEditingController _manualCodeCtrl = TextEditingController();

  bool _processing = false;
  bool _torchOn = false;
  String? _lastCode;
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  Future<void> _camera(bool start) async {
    try {
      if (start) {
        await _controller.start();
      } else {
        await _controller.stop();
      }
    } catch (_) {
      /* Manual entry remains available when camera access is denied. */
    }
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    unawaited(_camera(state == AppLifecycleState.resumed && !_processing));
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    _controller.dispose();
    _manualCodeCtrl.dispose();
    super.dispose();
  }

  /// Extracts a voucher code from whatever the QR contains:
  /// raw code ("REKI-ABC123"), JSON payload, or a deep link/URL.
  Future<void> _handleRawScan(String raw) async {
    if (_processing) return;
    final code = VoucherScan.parse(raw);
    if (code == null) {
      setState(() => _processing = true);
      await _showResult(success: false, message: 'Unrecognised QR code');
      if (mounted) setState(() => _processing = false);
      return;
    }
    if (code == _lastCode) return;
    _lastCode = code;
    await _redeem(code);
  }

  Future<void> _redeem(String code) async {
    if (_processing) return;
    final timing = developer.TimelineTask()
      ..start('reki.qr.decode_to_confirmation');
    setState(() => _processing = true);
    await _camera(false);
    if (!mounted) {
      timing.finish();
      return;
    }
    var timingFinished = false;
    try {
      if (widget.venueId == null || widget.venueId!.isEmpty) {
        await _showResult(
            success: false,
            message: 'Choose an assigned venue before scanning.');
        return;
      }
      final api = ref.read(offerApiServiceProvider);
      final data = await api.redeemByCode(code, venueId: widget.venueId);
      timing.finish(arguments: {'confirmed': true});
      timingFinished = true;
      if (!mounted) return;
      final title = (data['offer'] is Map
              ? (data['offer'] as Map)['title']
              : data['offerTitle'])
          ?.toString();
      final saving = data['savingValue']?.toString();
      final txn = data['transactionId']?.toString();
      await _showResult(
        success: true,
        message: title != null ? 'Redeemed: $title' : 'Offer redeemed!',
        detail: [
          if (saving != null) 'Customer saves £$saving',
          if (txn != null) 'TXN: $txn',
          'Code: $code',
        ].join('\n'),
      );
    } catch (e) {
      if (!mounted) return;
      await _showResult(
          success: false,
          message: 'Redemption failed',
          detail: _friendlyError(e));
    } finally {
      if (!timingFinished) timing.finish(arguments: {'confirmed': false});
      if (mounted) {
        setState(() => _processing = false);
        if (WidgetsBinding.instance.lifecycleState ==
            AppLifecycleState.resumed) {
          await _camera(true);
        }
      }
    }
  }

  String _friendlyError(Object e) {
    if (e is DioException &&
        (e.type == DioExceptionType.receiveTimeout ||
            e.type == DioExceptionType.connectionError)) {
      return 'Could not confirm redemption. Check its status before scanning again.';
    }
    if (e is StateError) return e.message;
    final msg = e.toString();
    if (msg.contains('404')) {
      return 'Staff redemption is unavailable, or voucher not found — check the code.';
    }
    if (msg.contains('400') || msg.contains('409') || msg.contains('422')) {
      return 'Voucher already redeemed or not valid for this venue.';
    }
    if (msg.contains('401') || msg.contains('403')) {
      return 'Not authorised — sign in with a staff/business account.';
    }
    return 'Please try again.';
  }

  Future<void> _showResult({
    required bool success,
    required String message,
    String? detail,
  }) async {
    await showModalBottomSheet<void>(
      context: context,
      isDismissible: false,
      backgroundColor: const Color(0xFF1E293B),
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
      ),
      builder: (ctx) => Padding(
        padding: const EdgeInsets.fromLTRB(24, 24, 24, 32),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(
              success ? Icons.check_circle : Icons.error_outline,
              color: success ? const Color(0xFF10B981) : Colors.redAccent,
              size: 64,
            ),
            const SizedBox(height: 12),
            Text(message,
                textAlign: TextAlign.center,
                style: const TextStyle(
                    color: Colors.white,
                    fontSize: 18,
                    fontWeight: FontWeight.w700)),
            if (detail != null) ...[
              const SizedBox(height: 8),
              Text(detail,
                  textAlign: TextAlign.center,
                  style:
                      const TextStyle(color: Color(0xFF94A3B8), fontSize: 13)),
            ],
            const SizedBox(height: 20),
            SizedBox(
              width: double.infinity,
              height: 50,
              child: ElevatedButton(
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppTheme.primaryColor,
                  foregroundColor: AppTheme.darkBg,
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(14)),
                ),
                onPressed: () {
                  Navigator.of(ctx).pop();
                  _manualCodeCtrl.clear();
                },
                child: const Text('Scan Next',
                    style: TextStyle(fontWeight: FontWeight.w700)),
              ),
            ),
          ],
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF0F172A),
      appBar: AppBar(
        backgroundColor: const Color(0xFF1E293B),
        elevation: 0,
        iconTheme: const IconThemeData(color: Colors.white),
        title: const Text('Scan Customer QR',
            style: TextStyle(
                color: Colors.white,
                fontSize: 17,
                fontWeight: FontWeight.w700)),
        actions: [
          IconButton(
            icon: Icon(_torchOn ? Icons.flash_on : Icons.flash_off,
                color: _torchOn ? const Color(0xFFF59E0B) : Colors.white),
            onPressed: () {
              _controller.toggleTorch();
              setState(() => _torchOn = !_torchOn);
            },
          ),
        ],
      ),
      body: Column(
        children: [
          Expanded(
            flex: 5,
            child: Stack(
              alignment: Alignment.center,
              children: [
                MobileScanner(
                  controller: _controller,
                  errorBuilder: (context, error) => const Center(
                      child: Padding(
                          padding: EdgeInsets.all(24),
                          child: Text(
                              'Camera unavailable. Enable camera access in Settings or enter the voucher code below.',
                              textAlign: TextAlign.center))),
                  onDetect: (capture) {
                    if (_processing) return;
                    for (final barcode in capture.barcodes) {
                      final raw = barcode.rawValue;
                      if (raw != null && raw.isNotEmpty) {
                        _handleRawScan(raw);
                        break;
                      }
                    }
                  },
                ),
                _ScanOverlay(processing: _processing),
              ],
            ),
          ),
          Expanded(
            flex: 4,
            child: Container(
              width: double.infinity,
              padding: const EdgeInsets.all(20),
              decoration: const BoxDecoration(
                color: Color(0xFF1E293B),
                borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text('ENTER CODE MANUALLY',
                      style: TextStyle(
                          color: Color(0xFF64748B),
                          fontSize: 11,
                          fontWeight: FontWeight.w800,
                          letterSpacing: 1.5)),
                  const SizedBox(height: 12),
                  TextField(
                    controller: _manualCodeCtrl,
                    textCapitalization: TextCapitalization.characters,
                    style: const TextStyle(
                        color: Colors.white, letterSpacing: 1.5),
                    decoration: InputDecoration(
                      hintText: 'REKI-ABC123',
                      hintStyle: const TextStyle(color: Color(0xFF475569)),
                      filled: true,
                      fillColor: const Color(0xFF0F172A),
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(12),
                        borderSide: const BorderSide(color: Color(0xFF334155)),
                      ),
                      enabledBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(12),
                        borderSide: const BorderSide(color: Color(0xFF334155)),
                      ),
                    ),
                  ),
                  const SizedBox(height: 12),
                  SizedBox(
                    width: double.infinity,
                    height: 48,
                    child: ElevatedButton.icon(
                      style: ElevatedButton.styleFrom(
                        backgroundColor: AppTheme.primaryColor,
                        foregroundColor: AppTheme.darkBg,
                        shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(12)),
                      ),
                      onPressed: _processing
                          ? null
                          : () {
                              final code = _manualCodeCtrl.text.trim();
                              if (code.isNotEmpty) {
                                _lastCode = null;
                                _handleRawScan(code);
                              }
                            },
                      icon: const Icon(Icons.redeem),
                      label: const Text('Redeem Code',
                          style: TextStyle(fontWeight: FontWeight.w700)),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

/// Corner-bracket viewfinder overlay.
class _ScanOverlay extends StatelessWidget {
  final bool processing;
  const _ScanOverlay({required this.processing});

  @override
  Widget build(BuildContext context) {
    const size = 240.0;
    return Container(
      color: Colors.black.withValues(alpha: 0.35),
      child: Center(
        child: SizedBox(
          width: size,
          height: size,
          child: Stack(
            children: [
              if (processing)
                const Center(
                  child: CircularProgressIndicator(
                      color: AppTheme.primaryColor, strokeWidth: 3),
                )
              else ...[
                _corner(const BorderRadius.only(topLeft: Radius.circular(12)),
                    Alignment.topLeft),
                _corner(const BorderRadius.only(topRight: Radius.circular(12)),
                    Alignment.topRight),
                _corner(
                    const BorderRadius.only(bottomLeft: Radius.circular(12)),
                    Alignment.bottomLeft),
                _corner(
                    const BorderRadius.only(bottomRight: Radius.circular(12)),
                    Alignment.bottomRight),
              ],
            ],
          ),
        ),
      ),
    );
  }

  Widget _corner(BorderRadius radius, Alignment alignment) {
    return Align(
      alignment: alignment,
      child: Container(
        width: 44,
        height: 44,
        decoration: BoxDecoration(
          borderRadius: radius,
          border: Border(
            top: alignment.y < 0
                ? const BorderSide(color: AppTheme.primaryColor, width: 4)
                : BorderSide.none,
            bottom: alignment.y > 0
                ? const BorderSide(color: AppTheme.primaryColor, width: 4)
                : BorderSide.none,
            left: alignment.x < 0
                ? const BorderSide(color: AppTheme.primaryColor, width: 4)
                : BorderSide.none,
            right: alignment.x > 0
                ? const BorderSide(color: AppTheme.primaryColor, width: 4)
                : BorderSide.none,
          ),
        ),
      ),
    );
  }
}
